### ISSUE TITLE
solov2：  KeyError: 'instances'

### ISSUE THREAD

**Issue by Ywenjun123** [jinfagang/yolov7_d2#109]
def preprocess_image(self, batched_inputs):
        for a in batched_inputs:
            img = a["image"].cpu().permute(1, 2, 0).numpy().astype(np.uint8)
            **ins = a['instances']**
            bboxes = ins.gt_boxes.tensor.cpu().numpy().astype(int)
            clss = ins.gt_classes.cpu().numpy()
            im = img.copy()
            bit_masks = ins.gt_masks.tensor.cpu().numpy()
            im = vis_bitmasks(im, bit_masks)
            im = visualize_det_cv2_part(im, None, clss, bboxes, is_show=False)

KeyError: 'instances'

**Comment by Sahil028** [comment]
@Ywenjun123 I also faced the same issue while predicting with solov2_lite and when I commented and ran, It was giving empty masks, were you able to solve it for predicting the masks ?

**Comment by jinfagang** [comment]
using train_instseg to train instance segmentation,
