### ISSUE TITLE
Feature Request: add Torch.Hub support

### ISSUE THREAD

**Issue by kadirnar** [jinfagang/yolov7_d2#153]
Hi @jinfagang,

- [ ] Can you add pypi or torch.hub support?

**Comment by kadirnar** [comment]
Hi, @jinfagang 

I want this library using PYPI. How should I write the reference code? Is there sample documentation? I want to add this library SAHI and tracking (deepsort, strongsort and bytetrack) algorithms.

**Comment by jinfagang** [comment]
Please take a look at readme.

**Comment by kadirnar** [comment]
Hi @jinfagang ,

I read the readme file, but I couldn't find the prediction code for pypi. There are only demo.py usage instructions.

Example Documentation: (Yolov5)
- https://github.com/fcakyon/yolov5-pip#use-from-python
-  https://docs.ultralytics.com/tutorials/pytorch-hub/

I want to make predictions without using demo.py. Isn't there a simple version of this?
