### ISSUE TITLE
How to inference onnx

### ISSUE THREAD

**Issue by UPwangcheng** [jinfagang/yolov7_d2#161]
Hello, thank you for your nice work.

I trained sparseinst and use export.py to generate onnx model successfully.

However, I find there is no script to inference image using onnx, I tried coding but the result is not the same as pth. I have no idea if the input formate is incorrect or something wrong include predictor and onnx.

If there are example scripts to inference image using onnx?

Thank you.

**Comment by jinfagang** [comment]
https://github.com/jinfagang/yolov7_d2/blob/main/deploy/ort_infer.py
