### ISSUE TITLE
How to implement a pose estimation model?

### ISSUE THREAD

**Issue by tctco** [jinfagang/yolov7_d2#176]
Is there a configuration or script that I can train a pose estimation model easily?

**Comment by jinfagang** [comment]
Hi, we will release our pose model very soon, model still under finetuning.

**Comment by tctco** [comment]
Hi! Thanks for your reply!

I found this [yolox_kpts_head.py](https://github.com/jinfagang/yolov7_d2/blob/main/yolov7/modeling/head/yolox_kpts_head.py) in your repo, and I'm using it to train on my custom dataset :) However, it seems that the model is trained from scratch. Is it possible to do a transfer learning?

Thanks in advance!

**Comment by jinfagang** [comment]
that code is not decent version, it's not trainable, we will opensource our pose model soon.

**Comment by tctco** [comment]
Get it. BTW, it seems that the current version for pose estimation is based on YOLO-Pose. Is that right?

Thanks!

**Comment by jinfagang** [comment]
Yes. YOLOX-Pose, it also same idea as yolov7-pose

**Comment by tctco** [comment]
Get it. Thanks! 

I'm also trying the instance segmentation model `yolomask`. However, I don't know how to load pre-trained weights. I tried downloading the original YOLOX-s pre-trained model and set `WEIGHTS: "./weights/yolox_s.pth"` but it didn't work (`WARNING [08/31 23:09:46 d2.checkpoint.c2_model_loading]: No weights in checkpoint matched with model.`). Besides, I don't know why it takes more GPU memory during evaluation than training. The related issue https://github.com/jinfagang/yolov7_d2/issues/154 has been closed, though.

**Comment by jinfagang** [comment]
if want try yolomask, please join our discord for further discuss, I can guide you how to make a powerful instance seg based on more decent detection arch. (with OrienMask head)

**Comment by tctco** [comment]
I tried to join the qq chat group but received no response days ago. The number of members in the wechat group has reached the limit. Where can I find the discord channel?

Thanks!

**Comment by jinfagang** [comment]
https://discord.gg/2E8AfjaEXM

**Comment by tctco** [comment]
Seems no one is active on the discord :(

I wonder how much data is required for training `yolomask`. I have a rather small and custom dataset which contains 200 training images and 50 for validation. However, the trained model is not predicting masks :(

**Comment by jinfagang** [comment]
discord some times have people

**Comment by tctco** [comment]
It seems that this line https://github.com/jinfagang/yolov7_d2/blob/main/demo.py#L145 should be

```python
clss = ins.pred_classes.cpu().numpy().astype(int)
```

or there will be this error `TypeError: list indices must be integers or slices, not numpy.float32`.

Besides, it seems that the segmented mask is not remapped to the original image size, don't know how to fix this:

![image](https://user-images.githubusercontent.com/45505657/188320157-87cccebd-cbcb-4561-95d4-a36c823a8c2a.png)

**Comment by jinfagang** [comment]
are u using orienmask? it should be able to align.

**Comment by tctco** [comment]
yes. I modified the config file based on the youtube video
