### ISSUE TITLE
can't import module 

### ISSUE THREAD

**Issue by chelsea456** [jinfagang/yolov7_d2#180]
when i run: python3 demo.py --config-file configs/wearmask/darknet53.yaml --input ./datasets/wearmask/images/val2017 --opts MODEL.WEIGHTS output/model_0009999.pth
it has issues    from detectron2.utils.logger import log_first_n
ModuleNotFoundError: No module named 'detectron2.utils'
sir can teach me how to fix prolem

**Comment by jinfagang** [comment]
https://github.com/facebookresearch/detectron2/tree/main/detectron2/utils
